# Generated by Django 3.2.4 on 2021-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='discussion',
            field=models.ManyToManyField(to='discussion.Discussion'),
        ),
    ]
