# Generated by Django 3.2.4 on 2021-06-21 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_tags_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='discussion',
            field=models.ManyToManyField(blank=True, null=True, to='discussion.Discussion'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
